servers:
  web:
    hosts:
      - dev.slovensko.digital

env:
  clear:
    RAILS_ENV: staging
    RAILS_LOG_LEVEL: info
    APP_HOST: agp.dev.slovensko.digital
    AUTOGRAM_BASE_URL: http://ag_service:7200

proxy:
  host: agp.dev.slovensko.digital

volumes:
  - "autogram_portal_storage:/rails/storage"

ssh:
  user: kamal
